
spring.application.name=HotelMangement

spring.datasource.url=jdbc:mysql://localhost:3306/ToDO?createDatabaseIfNotExist=true

spring.datasource.password=root
spring.datasource.username=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
